geth:
  deployment:
    name: "geth"
    image:
      repository: ethereum/client-go
      pullPolicy: Always
      tag: "v1.10.26"
      digest: "sha256:6789a4f29f5c4aa1e7b52b3b2cbe35d77544cf18e33ba6c6d600f162633e3301"
      pullSecret: ""
    replicas: 1
    commandArgs:
      - "--datadir"
      - "/data/"
      - "--http"
      - "--http.addr"
      - "0.0.0.0"
      - "--authrpc.jwtsecret"
      - "/secret/jwt.hex"
      - "--authrpc.addr"
      - "0.0.0.0"
      - "--authrpc.vhosts"
      - "*"
    podAnnotations: {}
    podSecurityContext: {}
    securityContext: {}

  service:
    name: "geth"
    type: ClusterIP
    annotations: {}

  serviceAccount:
    create: true
    annotations: {}
    name: "geth"

prysm:
  deployment:
    name: "prysm"
    image:
      repository: gcr.io/prysmaticlabs/prysm/beacon-chain
      pullPolicy: Always
      tag: "v3.1.2"
      digest: "sha256:140aa344814fee97a5ef9ee873e69f4c851972b388588f74ea7d26b4842dc9c3"
      pullSecret: ""
    replicas: 1
    commandArgs:
      - "--execution-endpoint=http://geth.default.svc.cluster.local:8551"
      - "--jwt-secret=/secret/jwt.hex"
      - "--accept-terms-of-use"
      - "--datadir"
      - "/data/"
      - "--checkpoint-sync-url=https://goerli.beaconstate.info/"
      - "--genesis-beacon-api-url=https://goerli.beaconstate.ethstaker.cc/"
    podAnnotations: {}
    podSecurityContext: {}
    securityContext: {}

  serviceAccount:
    create: true
    annotations: {}
    name: "prysm"
