{{- if .Values.geth.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.geth.serviceAccount.name }}
  labels:
    {{- include "eth-node.labels" . | nindent 4 }}
  {{- with .Values.geth.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
