{{- if .Values.prysm.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.prysm.serviceAccount.name }}
  labels:
    {{- include "eth-node.labels" . | nindent 4 }}
  {{- with .Values.prysm.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
