apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  # retrieve the secret data using lookup function and when not exists, return an empty dictionary / map as result
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "jwt.hex") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  # set $jwtSecret to existing secret data or generate a random one when not exists
  {{- $jwtSecret := (get $secretData "jwt.hex") | default (include "eth-node.randHex" 64 | b64enc) }}
  jwt.hex: {{ $jwtSecret | quote }}
